safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/vesc/low_level/ackermann_cmd"
    output_topic: "/vesc/low_level/input/safety"
    margin: 0.25
    max_deceleration: 2.0
    cone_angle: 5.
    car_width: 0.25
    lidar_offset: 0.13
