particle_filter:
  ros__parameters:
    particle_filter_frame: /pf/pose/odom
    odom_topic: /vesc/odom
    scan_topic: /scan
    map_topic: /map
    num_particles: 500
    num_beams_per_particle: 150
    scan_field_of_view: 4.71 # radians
    scan_theta_discretization: 500.0
    angle_step: 11
    deterministic: false
    debug: false
    lidar_scale_to_map_scale: 1.0
    motion_model:
      sigma_x: 0.15
      sigma_y: 0.06
      sigma_theta: 0.04

final_detector:
  ros__parameters:
    model: yolo11n.pt
    conf_threshold: 0.40
    iou_threshold: 0.7

traffic_light_node:
  ros__parameters:
    stop_distance: 1.0
    drive_topic: /vesc/high_level/input/nav_0

trajectory_planner:
  ros__parameters:
    odom_topic: /pf/pose/odom
    map_topic: /map
    scan_topic: /scan

trajectory_follower:
  ros__parameters:
    odom_topic: /pf/pose/odom
    drive_topic: /vesc/high_level/input/nav_2 
    base_lookahead: 1.50
    k_curve: 1.0
    velocity: 0.5
    goal_threshold: 0.5
    n_segments_to_weight: 2
    weight_decay: 0.8

parking_controller:
  ros__parameters:
    drive_topic: /vesc/high_level/input/nav_1
    velocity: 0.5
    parking_distance: 1.0
    distance_threshold: 0.20
    angle_threshold: 0.15
    visualize_parking: true

safety_controller:
  ros__parameters:
    drive_topic: /vesc/low_level/ackermann_cmd
    output_topic: /vesc/low_level/input/safety
    scan_topic: /scan
    min_obstacle_points: 15
    margin: 0.2
    max_deceleration: 2.0
    car_width: 0.25
    wheelbase: 0.325
    lidar_offset: 0.15
    visualize: true

boating_school_state_machine:
  ros__parameters:
    mcl_initialization_time: 5.0
