trajectory_planner:
  ros__parameters:
    odom_topic: "/odom"
    map_topic: "/map"
    scan_topic: "/scan"
    wall_buffer_m: 0.3
trajectory_follower:
  ros__parameters:
    odom_topic: "/odom"
    drive_topic: "/drive"
