particle_filter:
  ros__parameters:
    num_particles: 100
    num_beams_per_particle: 99
    scan_field_of_view: 4.71
    scan_theta_discretization: 500.0
    map_topic: "/map"
    scan_topic: "/scan"
    odom_topic: "/vesc/odom"
    particle_filter_frame: "pf/base_link"
    deterministic: false
    debug: false
    lidar_scale_to_map_scale: 1.0
    motion_model:
      sigma_x: 0.03
      sigma_y: 0.01
      sigma_theta: 0.04
